version: "3.9"
services:
  logger:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ "python", "src/main_logger.py" ]
    #restart: unless-stopped
    volumes:
      - .:/usr/src/app

  announcer:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ "python", "src/main_announcer.py" ]
    volumes:
      - .:/usr/src/app
